Repository acl-services/paprika, pull requests merged in 2019-11, with the labels that each got.

#213 Ux 588 list box browser
  packages/L10n/src/locales-js/en.js
  packages/L10n/src/locales/en.yml
  packages/ListBox/src/components/Box/Box.js
  packages/ListBox/src/components/Content/Content.js
  packages/ListBox/src/components/Option/Option.js
  packages/ListBox/src/components/Options/helpers/options.js
  packages/ListBox/src/components/Trigger/Trigger.js
  packages/ListBox/src/components/Trigger/Trigger.styles.js
  packages/ListBox/src/hooks/hooks.js
  packages/ListBox/stories/examples/multi.js
  packages/ListBox/stories/multi.stories.js
  packages/ListBoxBrowser/.npmignore
  packages/ListBoxBrowser/README.md
  packages/ListBoxBrowser/package.json
  packages/ListBoxBrowser/src/ListBoxBrowser.js
  packages/ListBoxBrowser/src/ListBoxBrowser.styles.js
  packages/ListBoxBrowser/src/components/Breadcrumb/Breadcrumb.js
  packages/ListBoxBrowser/src/components/Breadcrumb/Breadcrumb.styles.js
  packages/ListBoxBrowser/src/components/Breadcrumb/index.js
  packages/ListBoxBrowser/src/components/Browser/Browser.js
  packages/ListBoxBrowser/src/components/Browser/index.js
  packages/ListBoxBrowser/src/components/CustomListBox/CustomListBox.js
  packages/ListBoxBrowser/src/components/CustomListBox/CustomListBox.styles.js
  packages/ListBoxBrowser/src/components/CustomListBox/helpers.js
  packages/ListBoxBrowser/src/components/CustomListBox/index.js
  packages/ListBoxBrowser/src/components/OptionsSelected/OptionsSelected.js
  packages/ListBoxBrowser/src/components/OptionsSelected/OptionsSelected.styles.js
  packages/ListBoxBrowser/src/components/OptionsSelected/index.js
  packages/ListBoxBrowser/src/components/Root/Root.js
  packages/ListBoxBrowser/src/components/Root/index.js
  packages/ListBoxBrowser/src/components/Title/Title.js
  packages/ListBoxBrowser/src/components/Title/Title.styles.js
  packages/ListBoxBrowser/src/components/Title/index.js
  packages/ListBoxBrowser/src/helpers.js
  packages/ListBoxBrowser/src/index.js
  packages/ListBoxBrowser/stories/ListBoxBrowser.multiple.stories.js
  packages/ListBoxBrowser/stories/ListBoxBrowser.single.stories.js
  packages/ListBoxBrowser/stories/examples/Lazy.js
  packages/ListBoxBrowser/test/cypress/basic.cypress.js
  packages/ListBoxBrowser/test/specs/ListBoxBrowser.spec.js
  packages/ListBoxBrowser/test/specs/__snapshots__/ListBoxBrowser.spec.js.snap
  packages/ListBoxBrowser/test/specs/fixtures/issues.js
  packages/ListBoxBrowser/test/specs/fixtures/multiple.firstOptionNoOptions.js
  packages/ListBoxBrowser/test/specs/fixtures/multiple.js
  packages/ListBoxBrowser/test/specs/fixtures/multiple.withNoOptions.js
  packages/ListBoxBrowser/test/specs/fixtures/single.js
  packages/ListBoxBrowser/test/specs/fixtures/withNoOptionsSelected.js
  yarn.lock
Labels: New Component

#214 UX-565 Takeover component migration
  .eslintrc
  jest.config.js
  package.json
  packages/Button/src/Button.styles.js
  packages/FormElement/src/FormElement.js
  packages/SidePanel/src/SidePanel.js
  packages/SidePanel/src/components/LockBodyScroll.js
  packages/SidePanel/src/hooks/index.js
  packages/SidePanel/src/hooks/useEscapeKey.js
  packages/Takeover/.npmignore
  packages/Takeover/README.md
  packages/Takeover/package.json
  packages/Takeover/src/Takeover.js
  packages/Takeover/src/Takeover.styles.js
  packages/Takeover/src/components/Content.js
  packages/Takeover/src/components/FocusTrap.js
  packages/Takeover/src/components/Header.js
  packages/Takeover/src/components/Header.styles.js
  packages/Takeover/src/helpers/tokens.js
  packages/Takeover/src/index.js
  packages/Takeover/stories/Takeover.stories.js
  packages/Takeover/tests/Takeover.spec.js
  packages/helpers/src/components/LockBodyScroll.js
  packages/helpers/src/components/Portal.js
  packages/helpers/src/extractChildren.js
  testingHelpers/config.js
  yarn.lock
Labels: Flatstack, New Component

#283 UX-628 Experimenting with DocPages and MDX in CollapsibleText stories 🐐
  .storybook/assets/styles/common.styles.js
  .storybook/config.js
  .storybook/presets.js
  package.json
  packages/CollapsibleText/stories/CollapsibleText.Tests.stories.js
  packages/CollapsibleText/stories/CollapsibleText.mdx
  packages/CollapsibleText/stories/CollapsibleText.stories.js
  packages/CollapsibleText/stories/CollapsibleText.stories.mdx
  packages/CollapsibleText/stories/examples/Showcase.js
  packages/CollapsibleText/stories/examples/Variations.js
  packages/Counter/stories/examples/SizesTypes.js
  packages/Popover/stories/examples/A11y.js
  packages/Popover/stories/examples/Screener.js
  packages/Tabs/stories/Tabs.stories.js
  yarn.lock
Labels: Documentation, Proposal

#279 Updates to PR template 🐐
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, Proposal
