Repository acl-services/paprika, pull requests merged in 2020-12, with the labels that each got.

#826 feat(StatusTracker): UXD-470 add component
  .storybook/storyTree.js
  packages/OverflowMenu/README.md
  packages/OverflowMenu/src/OverflowMenu.js
  packages/OverflowMenu/src/index.d.ts
  packages/OverflowMenu/test/overflowMenu.spec.js
  packages/StatusTracker/.npmignore
  packages/StatusTracker/CHANGELOG.md
  packages/StatusTracker/README.md
  packages/StatusTracker/package.json
  packages/StatusTracker/src/StatusTracker.js
  packages/StatusTracker/src/StatusTracker.styles.js
  packages/StatusTracker/src/components/Point/Point.js
  packages/StatusTracker/src/components/Point/Point.styles.js
  packages/StatusTracker/src/components/Point/index.js
  packages/StatusTracker/src/index.d.ts
  packages/StatusTracker/src/index.js
  packages/StatusTracker/src/types.js
  packages/StatusTracker/stories/StatusTracker.mdx
  packages/StatusTracker/stories/StatusTracker.stories.js
  packages/StatusTracker/stories/StatusTracker.stories.mdx
  packages/StatusTracker/stories/StatusTracker.tests.stories.js
  packages/StatusTracker/stories/examples/Showcase.js
  packages/StatusTracker/tests/StatusTracker.spec.js
  packages/helpers/src/extractChildren.js
Labels: New Component

#835 UXD-601 FormElement fixes and documentation updates 🐐
  packages/FormElement/CHANGELOG.md
  packages/FormElement/README.md
  packages/FormElement/src/FormElement.js
  packages/FormElement/src/components/Content/Content.js
  packages/FormElement/src/components/Description/Description.js
  packages/FormElement/src/components/Error/Error.js
  packages/FormElement/src/components/Error/Error.styles.js
  packages/FormElement/src/components/Fieldset/Fieldset.js
  packages/FormElement/src/components/Help/Help.js
  packages/FormElement/src/components/Help/Help.styles.js
  packages/FormElement/src/components/Instructions/Instructions.js
  packages/FormElement/src/components/Label/Label.js
  packages/FormElement/src/components/Label/Label.styles.js
  packages/FormElement/src/components/Layout/Layout.js
  packages/FormElement/src/components/Layout/LeftCol/LeftCol.js
  packages/FormElement/src/components/Layout/LeftCol/LeftCol.styles.js
  packages/FormElement/src/components/Layout/RightCol/RightCol.js
  packages/FormElement/src/index.d.ts
  packages/FormElement/stories/FormElement.examples.stories.js
  packages/FormElement/stories/FormElement.stories.mdx
  packages/FormElement/stories/examples/Accessibility.js
  packages/FormElement/stories/examples/ButtonGroup.js
  packages/FormElement/stories/examples/Checkbox.js
  packages/FormElement/stories/examples/ComponentLabel.js
  packages/FormElement/stories/examples/DatePicker.js
  packages/FormElement/stories/examples/Everything.js
  packages/FormElement/stories/examples/Fieldset.js
  packages/FormElement/stories/examples/HTML.js
  packages/FormElement/stories/examples/Inline.js
  packages/FormElement/stories/examples/InlineContent.js
  packages/FormElement/stories/examples/ListBox.js
  packages/FormElement/stories/examples/NativeInput.js
  packages/FormElement/stories/examples/Nested.js
  packages/FormElement/stories/examples/Radio.js
  packages/FormElement/stories/examples/Showcase.js
  packages/FormElement/stories/examples/Subcomponents.js
  packages/FormElement/stories/examples/Variations.js
  packages/FormElement/tests/FormElement.spec.js
Labels: Breaking Changes 💥, Bug 🐞, Documentation

#850 feature(Uploader): UXD-636 add custom error handler and remover retry
  package.json
  packages/L10n/src/locales/en.yml
  packages/Uploader/CHANGELOG.md
  packages/Uploader/README.md
  packages/Uploader/src/Uploader.js
  packages/Uploader/src/components/File/File.js
  packages/Uploader/src/components/File/File.styles.js
  packages/Uploader/src/components/FileList/FileList.js
  packages/Uploader/src/helpers.js
  packages/Uploader/src/index.d.ts
  packages/Uploader/src/useProcessFiles.js
  packages/Uploader/stories/Uploader.stories.js
  packages/Uploader/tests/Uploader.cypress.js
Labels: Breaking Changes 💥
