Repository acl-services/paprika, pull requests merged in 2020-11, with the labels that each got.

#759 UXD-427 Add README and Docs pages for Tokens + Stylers 🐐
  .storybook/storyTree.js
  packages/Stylers/README.md
  packages/Stylers/stories/Stylers.sass.stories.js
  packages/Stylers/stories/Stylers.stories.js
  packages/Stylers/stories/Stylers.stories.mdx
  packages/Stylers/stories/Stylers.stories.styles.js
  packages/Stylers/stories/sass-helpers.stories.js
  packages/Stylers/stories/stylers.stories.js
  packages/Tokens/README.md
  packages/Tokens/stories/Tokens.stories.mdx
Labels: Documentation

#776 UXD-468 Add collapsible card component
  .storybook/storyTree.js
  packages/Collapsible/README.md
  packages/Collapsible/src/Collapsible.js
  packages/Collapsible/src/index.d.ts
  packages/CollapsibleCard/.npmignore
  packages/CollapsibleCard/CHANGELOG.md
  packages/CollapsibleCard/README.md
  packages/CollapsibleCard/package.json
  packages/CollapsibleCard/src/CollapsibleCard.js
  packages/CollapsibleCard/src/CollapsibleCard.styles.js
  packages/CollapsibleCard/src/components/Avatar/Avatar.js
  packages/CollapsibleCard/src/components/Avatar/Avatar.styles.js
  packages/CollapsibleCard/src/components/Avatar/index.js
  packages/CollapsibleCard/src/components/Metadata/Metadata.js
  packages/CollapsibleCard/src/components/Metadata/Metadata.styles.js
  packages/CollapsibleCard/src/components/Metadata/index.js
  packages/CollapsibleCard/src/index.d.ts
  packages/CollapsibleCard/src/index.js
  packages/CollapsibleCard/stories/CollapsibleCard.stories.js
  packages/CollapsibleCard/stories/CollapsibleCard.stories.mdx
  packages/CollapsibleCard/stories/CollapsibleCard.tests.stories.js
  packages/CollapsibleCard/stories/examples/Showcase.js
  packages/CollapsibleCard/stories/examples/Variations.js
  packages/CollapsibleCard/tests/CollapsibleCard.spec.js
  packages/L10n/src/locales/en.yml
  yarn.lock
Labels: New Component

#771 UXD-458 Side bar nav
  .storybook/storyTree.js
  packages/Icon/src/svg/Menu.svg
  packages/L10n/src/locales/en.yml
  packages/SideNavigation/.npmignore
  packages/SideNavigation/CHANGELOG.md
  packages/SideNavigation/README.md
  packages/SideNavigation/package.json
  packages/SideNavigation/src/SideNavigation.js
  packages/SideNavigation/src/SideNavigation.styles.js
  packages/SideNavigation/src/components/Item/Item.js
  packages/SideNavigation/src/components/Item/Item.styles.js
  packages/SideNavigation/src/components/Item/index.js
  packages/SideNavigation/src/index.d.ts
  packages/SideNavigation/src/index.js
  packages/SideNavigation/stories/SideNavigation.mdx
  packages/SideNavigation/stories/SideNavigation.stories.js
  packages/SideNavigation/stories/SideNavigation.stories.mdx
  packages/SideNavigation/stories/SideNavigation.tests.stories.js
  packages/SideNavigation/stories/examples/Example.js
  packages/SideNavigation/stories/examples/Screener.js
  packages/SideNavigation/stories/examples/Showcase.js
  packages/SideNavigation/test/SideNavigation.spec.js
  packages/SidePanel/src/components/Content/Content.js
  packages/SidePanel/src/components/Dialog/Dialog.js
  packages/TimePicker/src/TimePicker.js
  yarn.lock
Labels: New Component

#815 Uxd 546 panel from below
  packages/Panel/CHANGELOG.md
  packages/Panel/README.md
  packages/Panel/src/Panel.js
  packages/Panel/src/components/Dialog/Dialog.js
  packages/Panel/src/components/Dialog/Dialog.styles.js
  packages/Panel/src/components/Header/Header.js
  packages/Panel/src/components/Trigger/Trigger.js
  packages/Panel/src/helpers.js
  packages/Panel/src/index.d.ts
  packages/Panel/src/types.js
  packages/Panel/stories/Panel.examples.stories.js
  packages/Panel/stories/examples/Cypress.js
  packages/Panel/stories/examples/Examples.js
  packages/Panel/stories/examples/Showcase.js
Labels: Breaking Changes 💥

#753 Uxd 374 list box tags
  .gitignore
  packages/ActionBar/tests/cypress/ActionBar.cypress.js
  packages/L10n/src/locales/en.yml
  packages/ListBox/README.md
  packages/ListBox/package.json
  packages/ListBox/src/WithTags.js
  packages/ListBox/src/components/Divider/Divider.styles.js
  packages/ListBox/src/components/Filter/Filter.js
  packages/ListBox/src/components/Options/helpers/options.js
  packages/ListBox/src/components/Pill/Pill.js
  packages/ListBox/src/components/Pill/Pill.styles.js
  packages/ListBox/src/components/Pill/index.js
  packages/ListBox/src/components/Trigger/Trigger.js
  packages/ListBox/src/components/WithTags/WithTags.js
  packages/ListBox/src/components/WithTags/WithTags.styles.js
  packages/ListBox/src/components/WithTags/index.js
  packages/ListBox/src/components/WithTags/useWithTags.js
  packages/ListBox/src/helpers/filter.js
  packages/ListBox/src/hooks/hooks.js
  packages/ListBox/src/imperative/imperative.js
  packages/ListBox/src/index.d.ts
  packages/ListBox/src/index.js
  packages/ListBox/stories/WithTags/ListBoxWithTags.controlled.stories.js
  packages/ListBox/stories/WithTags/ListBoxWithTags.sizes.screener.stories.js
  packages/ListBox/stories/WithTags/ListBoxWithTags.uncontrolled-custom-trigger.stories.js
  packages/ListBox/stories/WithTags/ListBoxWithTags.uncontrolled-users.stories.js
  packages/ListBox/stories/WithTags/ListBoxWithTags.uncontrolled.stories.js
  packages/ListBox/stories/WithTags/examples/Controlled.js
  packages/ListBox/stories/WithTags/examples/CustomTrigger.js
  packages/ListBox/stories/WithTags/examples/Sizes.js
  packages/ListBox/stories/WithTags/examples/Uncontrolled.js
  packages/ListBox/stories/WithTags/examples/UncontrolledUser.js
  packages/ListBox/stories/WithTags/mocks.js
  packages/ListBox/stories/examples/multi.js
  packages/ListBox/test/specs/withTags/__snapshots__/withTags.spec.js.snap
  packages/ListBox/test/specs/withTags/withTags.spec.js
Labels: New Component

#774 UXD-157 formElement component api refactor
  packages/Checkbox/CHANGELOG.md
  packages/Checkbox/README.md
  packages/Checkbox/src/Checkbox.js
  packages/Checkbox/src/index.d.ts
  packages/DatePicker/CHANGELOG.md
  packages/DatePicker/README.md
  packages/DatePicker/src/DatePicker.js
  packages/DatePicker/src/index.d.ts
  packages/FormElement/CHANGELOG.md
  packages/FormElement/README.md
  packages/FormElement/package.json
  packages/FormElement/src/FormElement.js
  packages/FormElement/src/FormElement.styles.js
  packages/FormElement/src/components/Content/Content.js
  packages/FormElement/src/components/Description/Description.js
  packages/FormElement/src/components/Error/Error.js
  packages/FormElement/src/components/Error/Error.styles.js
  packages/FormElement/src/components/Fieldset/Fieldset.js
  packages/FormElement/src/components/Fieldset/index.js
  packages/FormElement/src/components/Instructions/Instructions.js
  packages/FormElement/src/components/Label/Label.js
  packages/FormElement/src/components/Layout/Layout.js
  packages/FormElement/src/components/Layout/Layout.styles.js
  packages/FormElement/src/components/Layout/LeftCol/LeftCol.js
  packages/FormElement/src/components/Layout/LeftCol/LeftCol.styles.js
  packages/FormElement/src/components/Layout/RightCol/RightCol.js
  packages/FormElement/src/components/Layout/RightCol/RightCol.styles.js
  packages/FormElement/src/components/Layout/index.js
  packages/FormElement/src/index.d.ts
  packages/FormElement/src/index.js
  packages/FormElement/stories/FormElement.examples.stories.js
  packages/FormElement/stories/FormElement.stories.mdx
  packages/FormElement/stories/examples/Accessibility.js
  packages/FormElement/stories/examples/ButtonGroup.js
  packages/FormElement/stories/examples/Checkbox.js
  packages/FormElement/stories/examples/ComponentLabel.js
  packages/FormElement/stories/examples/DatePicker.js
  packages/FormElement/stories/examples/HTML.js
  packages/FormElement/stories/examples/InlineContent.js
  packages/FormElement/stories/examples/ListBox.js
  packages/FormElement/stories/examples/NativeInput.js
  packages/FormElement/stories/examples/Nested.js
  packages/FormElement/stories/examples/NestedExample.js
  packages/FormElement/stories/examples/Radio.js
  packages/FormElement/stories/examples/Showcase.js
  packages/FormElement/stories/examples/Variations.js
  packages/FormElement/tests/FormElement.spec.js
  packages/L10n/stories/examples/withLocales/FakeAppWithLocales.js
  packages/Radio/CHANGELOG.md
  packages/Radio/README.md
  packages/Radio/src/Radio.js
  packages/Radio/src/RadioInputPropsCollector.js
  packages/Radio/src/index.d.ts
  packages/TimePicker/stories/TimePicker.stories.js
Labels: Breaking Changes 💥
