Repository acl-services/paprika, pull requests merged in 2020-04, with the labels that each got.

#457 STAR-156 Extract DateInput as separate component
  packages/DateInput/README.md
  packages/DateInput/package.json
  packages/DateInput/src/DateInput.js
  packages/DateInput/src/index.js
  packages/DateInput/stories/DateInput.stories.js
  packages/DateInput/test/DateInput.spec.js
  packages/DatePicker/README.md
  packages/DatePicker/package.json
  packages/DatePicker/src/DatePicker.js
  packages/DatePicker/src/components/Calendar/Calendar.js
  packages/DatePicker/src/components/DateInputPropsCollector/DateInputPropsCollector.js
  packages/DatePicker/src/components/DateInputPropsCollector/index.js
  packages/DatePicker/src/components/DatePickerPopover/index.js
  packages/DatePicker/src/components/DatePickerPopoverPropsCollector/DatePickerPopoverPropsCollector.js
  packages/DatePicker/src/components/DatePickerPopoverPropsCollector/index.js
  packages/DatePicker/src/components/ShortcutPanel/ShortcutPanel.js
  packages/DatePicker/src/helpers.js
  packages/DatePicker/stories/DatePicker.stories.js
  packages/helpers/src/extractChildrenProps.js
Labels: Flatstack

#440 UX-575 upgrade to 6.0 alpha, refactor stories for sidepanel
  .storybook/config.js
  .storybook/reset.scss
  package.json
  packages/CollapsibleText/stories/CollapsibleText.stories.js
  packages/CollapsibleText/stories/CollapsibleText.stories.mdx
  packages/SidePanel/CHANGELOG.md
  packages/SidePanel/src/components/Overlay/Overlay.js
  packages/SidePanel/stories/SidePanel.FocusLock.stories.js
  packages/SidePanel/stories/SidePanel.Footer.stories.js
  packages/SidePanel/stories/SidePanel.Group.stories.js
  packages/SidePanel/stories/SidePanel.Header.stories.js
  packages/SidePanel/stories/SidePanel.Overlay.stories.js
  packages/SidePanel/stories/SidePanel.Tests.stories.js
  packages/SidePanel/stories/SidePanel.examples.stories.js
  packages/SidePanel/stories/SidePanel.mdx
  packages/SidePanel/stories/SidePanel.stories.js
  packages/SidePanel/stories/SidePanel.stories.mdx
  packages/SidePanel/stories/cypress.stories.js
  packages/SidePanel/stories/examples/Cypress.js
  packages/SidePanel/stories/examples/Examples.js
  packages/SidePanel/stories/examples/Showcase.js
  packages/SidePanel/tests/SidePanel.cypress.js
  packages/Toast/stories/Toast.examples.stories.js
  packages/Toast/stories/Toast.stories.js
  packages/Toast/stories/Toast.stories.mdx
  yarn.lock
Labels: Breaking Changes 💥

#492 STAR-199 Add zIndex props to layered components 🐐
  packages/Confirmation/src/Confirmation.js
  packages/DatePicker/src/components/DatePickerPopoverPropsCollector/DatePickerPopoverPropsCollector.js
  packages/DropdownMenu/src/DropdownMenu.js
  packages/DropdownMenu/stories/DropdownMenu.stories.js
  packages/DropdownMenu/stories/examples/ZIndex.js
  packages/Modal/src/Modal.js
  packages/Modal/stories/Modal.stories.js
  packages/Overlay/CHANGELOG.md
  packages/Overlay/src/Overlay.js
  packages/Overlay/src/Overlay.styles.js
  packages/Overlay/src/Wrapper.js
  packages/Overlay/src/index.js
  packages/Popover/src/Popover.js
  packages/SidePanel/src/SidePanel.js
  packages/SidePanel/src/components/Dialog/Dialog.js
  packages/SidePanel/src/components/Overlay/Overlay.js
  packages/SidePanel/src/components/Overlay/Overlay.styles.js
  packages/SidePanel/stories/SidePanel.examples.stories.js
  packages/SidePanel/stories/examples/Examples.js
  packages/SidePanel/stories/examples/Showcase.js
  packages/Takeover/src/Takeover.js
  packages/Takeover/src/Takeover.styles.js
  packages/Takeover/src/components/Header.js
  packages/Takeover/stories/Takeover.stories.js
Labels: Breaking Changes 💥

#506 STAR-220 Update Filter icon 🐐
  packages/Icon/CHANGELOG.md
  packages/Icon/src/svg/Filter-Alt.svg
  packages/Icon/src/svg/Filter.svg
Labels: Breaking Changes 💥

#401 UX-633 ActionBar component
  packages/ActionBar/.npmignore
  packages/ActionBar/README.md
  packages/ActionBar/package.json
  packages/ActionBar/src/ActionBar.js
  packages/ActionBar/src/ActionBar.styles.js
  packages/ActionBar/src/columnShape.js
  packages/ActionBar/src/components/ColumnsArrangement/ColumnDefinition.js
  packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangement.js
  packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangement.styles.js
  packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangementItem.js
  packages/ActionBar/src/components/ColumnsArrangement/index.js
  packages/ActionBar/src/components/Filter/DatePicker.js
  packages/ActionBar/src/components/Filter/Filter.js
  packages/ActionBar/src/components/Filter/Filter.styles.js
  packages/ActionBar/src/components/Filter/FilterItem.js
  packages/ActionBar/src/components/Filter/context.js
  packages/ActionBar/src/components/Filter/index.js
  packages/ActionBar/src/components/Filter/rules.js
  packages/ActionBar/src/components/InlineInput/InlineInput.js
  packages/ActionBar/src/components/InlineInput/InlineInput.styles.js
  packages/ActionBar/src/components/InlineSelect/InlineSelect.js
  packages/ActionBar/src/components/InlineSelect/InlineSelect.styles.js
  packages/ActionBar/src/components/Sort/Sort.js
  packages/ActionBar/src/components/Sort/Sort.styles.js
  packages/ActionBar/src/components/Sort/SortField.js
  packages/ActionBar/src/components/Sort/context.js
  packages/ActionBar/src/components/Sort/index.js
  packages/ActionBar/src/constants.js
  packages/ActionBar/src/hooks/useColumnsArragment/index.js
  packages/ActionBar/src/hooks/useColumnsArragment/useColumnsArragment.js
  packages/ActionBar/src/hooks/useFilter/index.js
  packages/ActionBar/src/hooks/useFilter/testers.js
  packages/ActionBar/src/hooks/useFilter/useFilter.js
  packages/ActionBar/src/hooks/useSort/getAlphaSortFunction.js
  packages/ActionBar/src/hooks/useSort/index.js
  packages/ActionBar/src/hooks/useSort/sort.js
  packages/ActionBar/src/hooks/useSort/useSort.js
  packages/ActionBar/src/index.js
  packages/ActionBar/stories/ShowcaseApp/CustomSingleSelectFilter.js
  packages/ActionBar/stories/ShowcaseApp/ShowcaseApp.js
  packages/ActionBar/stories/ShowcaseApp/data.js
  packages/ActionBar/stories/ShowcaseApp/index.js
  packages/ActionBar/stories/showcase.stories.js
  packages/Icon/src/svg/Hide.svg
  packages/Icon/src/svg/Sort.svg
  packages/Icon/src/svg/hide.svg
  packages/Icon/src/svg/sort.svg
  packages/L10n/src/locales/en.yml
  yarn.lock
Labels: New Component
