Repository acl-services/paprika, pull requests merged in 2021-02, with the labels that each got.

#918 UXD-803 docs(ListBox): added Showcase
  packages/ListBox/src/index.js
  packages/ListBox/stories/Filter.stories.js
  packages/ListBox/stories/ListBox.mdx
  packages/ListBox/stories/examples/Showcase.js
  packages/ListBox/stories/examples/multi.js
  packages/ListBox/stories/examples/single.js
  packages/ListBox/stories/listBox.stories.js
  packages/ListBox/stories/moreExamples/isDisabled/IsDisabled.js
  packages/ListBox/stories/moreExamples/isDisabled/IsDisabled.stories.js
  packages/ListBox/stories/multi.stories.js
  packages/ListBox/stories/single.stories.js
Labels: Documentation

#926 UXD-822 Fix clear button for uncontrolled Input 🐐
  packages/Input/CHANGELOG.md
  packages/Input/README.md
  packages/Input/package.json
  packages/Input/src/Input.js
  packages/Input/src/index.d.ts
  packages/Input/stories/Input.stories.js
  packages/Input/stories/examples/InputExample.js
  packages/Input/stories/examples/Showcase.js
  packages/Input/stories/examples/StateDecorator.js
  packages/Input/stories/examples/Uncontrolled.js
  packages/Input/stories/examples/WithRef.js
  packages/L10n/CHANGELOG.md
  packages/L10n/src/locales/en.yml
  packages/helpers/CHANGELOG.md
  packages/helpers/README.md
  packages/helpers/src/callAll.js
  packages/helpers/src/index.js
Labels: Breaking Changes 💥, Bug 🐞

#930 featre(seducer): UXD-630 initial commit seducer
  .storybook/components/Blocks/Blocks.js
  .storybook/components/Blocks/index.js
  .storybook/public/logger.gif
  .storybook/storyTree.js
  package.json
  packages/seducer/.npmignore
  packages/seducer/CHANGELOG.md
  packages/seducer/README.md
  packages/seducer/package.json
  packages/seducer/src/getTypes.js
  packages/seducer/src/index.js
  packages/seducer/src/logger.js
  packages/seducer/src/reducer.js
  packages/seducer/src/useSeducer.js
  packages/seducer/src/useSeducerWithContext.js
  packages/seducer/stories/examples/useReducer.basic.js
  packages/seducer/stories/examples/useReducer.confetti.js
  packages/seducer/stories/examples/useReducerWithContext.CharacterList.js
  packages/seducer/stories/examples/useReducerWithContext.basic.js
  packages/seducer/stories/examples/useSeducer.async.js
  packages/seducer/stories/seducer.stories.mdx
  packages/seducer/stories/seducer.useReducer.stories.js
  packages/seducer/stories/seducer.useReducerWithContext.stories.js
  yarn.lock
Labels: 📦 New Package

#935 feature(seducer): UXD-630 fixing package issue
  packages/seducer/CHANGELOG.md
  packages/seducer/package.json
Labels: Breaking Changes 💥

#954 UXD-867 ListBox compatibility with FormElement 🐐
  packages/ListBox/CHANGELOG.md
  packages/ListBox/README.md
  packages/ListBox/package.json
  packages/ListBox/src/ListBox.js
  packages/ListBox/src/components/A11y/A11y.js
  packages/ListBox/src/components/A11y/index.js
  packages/ListBox/src/components/Box/Box.js
  packages/ListBox/src/components/Box/Box.styles.js
  packages/ListBox/src/components/Content/Content.js
  packages/ListBox/src/components/Content/Content.styles.js
  packages/ListBox/src/components/Divider/Divider.js
  packages/ListBox/src/components/Divider/Divider.styles.js
  packages/ListBox/src/components/Filter/Filter.js
  packages/ListBox/src/components/Footer/Footer.js
  packages/ListBox/src/components/Label/Label.js
  packages/ListBox/src/components/Label/Label.styles.js
  packages/ListBox/src/components/List/List.js
  packages/ListBox/src/components/List/List.styles.js
  packages/ListBox/src/components/NoResults/NoResults.js
  packages/ListBox/src/components/Option/Option.js
  packages/ListBox/src/components/Option/Option.styles.js
  packages/ListBox/src/components/Options/helpers/options.js
  packages/ListBox/src/components/Trigger/Trigger.js
  packages/ListBox/src/components/Trigger/Trigger.styles.js
  packages/ListBox/src/helpers/DOMAttributes.js
  packages/ListBox/src/helpers/handleKeyboardKeys.js
  packages/ListBox/src/hooks/hooks.js
  packages/ListBox/src/index.d.ts
  packages/ListBox/src/index.js
  packages/ListBox/src/store/PropsProvider.js
  packages/ListBox/src/store/Provider.js
  packages/ListBox/src/store/actionTypes.js
  packages/ListBox/src/store/reducer.js
  packages/ListBox/stories/ListBox.examples.stories.js
  packages/ListBox/stories/ListBox.stories.mdx
  packages/ListBox/stories/examples/FormElement.js
  packages/ListBox/stories/examples/Showcase.js
  packages/ListBox/test/cypress/ListBox.cypress.js
  packages/ListBox/test/helpers/toggleHelpers.js
  packages/ListBoxBrowser/test/cypress/basic.cypress.js
  packages/ListBoxWithTags/src/ListBoxWithTags.js
  scripts/readmeFiles.js
Labels: A11y, Breaking Changes 💥
