Repository acl-services/paprika, pull requests merged in 2021-01, with the labels that each got.

#849 feature(Search): init UXD-596
  .storybook/storyTree.js
  packages/Icon/README.md
  packages/Input/src/Input.js
  packages/L10n/src/locales/en.yml
  packages/ListBox/src/ListBox.js
  packages/ListBox/src/components/List/List.js
  packages/ListBox/src/components/Options/helpers/options.js
  packages/ListBox/src/components/Trigger/Trigger.js
  packages/ListBox/src/helpers/filter.js
  packages/ListBox/src/helpers/invokeOnChange.js
  packages/ListBox/src/types.js
  packages/Search/.npmignore
  packages/Search/CHANGELOG.md
  packages/Search/README.MD
  packages/Search/package.json
  packages/Search/src/Search.js
  packages/Search/src/Search.styles.js
  packages/Search/src/index.d.ts
  packages/Search/src/index.js
  packages/Search/src/renderTrigger.js
  packages/Search/src/useTrigger.js
  packages/Search/stories/Search.basic.stories.js
  packages/Search/stories/Search.lazyLoading.stories.js
  packages/Search/stories/examples/Basic.js
  packages/Search/stories/examples/LazyLoading.js
  packages/Search/stories/examples/helpers.js
  packages/Search/tests/Search.spec.js
  scripts/readmeFiles.js
  yarn.lock
Labels: New Component

#868 Uxd 683 advanced filter
  .storybook/storyTree.js
  packages/Filter/.npmignore
  packages/Filter/CHANGELOG.md
  packages/Filter/README.md
  packages/Filter/package.json
  packages/Filter/src/Filter.js
  packages/Filter/src/Filter.styles.js
  packages/Filter/src/columnShape.js
  packages/Filter/src/components/DatePicker/DatePicker.js
  packages/Filter/src/components/DatePicker/index.js
  packages/Filter/src/components/FilterPrefix/FilterPrefix.js
  packages/Filter/src/components/FilterPrefix/FilterPrefix.styles.js
  packages/Filter/src/components/FilterPrefix/index.js
  packages/Filter/src/components/Item/FilterItem.styles.js
  packages/Filter/src/components/Item/Item.js
  packages/Filter/src/components/Item/index.js
  packages/Filter/src/context.js
  packages/Filter/src/helpers/filterData.js
  packages/Filter/src/helpers/getInitialValueByType.js
  packages/Filter/src/helpers/testers.js
  packages/Filter/src/hooks/defaultReducer.js
  packages/Filter/src/hooks/useFilter.js
  packages/Filter/src/index.d.ts
  packages/Filter/src/index.js
  packages/Filter/src/rules.js
  packages/Filter/src/types.js
  packages/Filter/stories/MockServerFilter/App.js
  packages/Filter/stories/MockServerFilter/CustomSingleSelectFilter.js
  packages/Filter/stories/MockServerFilter/api.js
  packages/Filter/stories/ShowcaseApp/ShowcaseApp.js
  packages/Filter/stories/ShowcaseApp/data.js
  packages/Filter/stories/ShowcaseApp/index.js
  packages/Filter/stories/serverSideFilters.stories.js
  packages/Filter/stories/showcase.stories.js
  packages/L10n/src/locales/en.yml
  packages/Radio/src/Radio.js
Labels: New Component

#869 feat(ActionBar): UXD-684 remove Filter in ActionBar
  packages/ActionBar/CHANGELOG.md
  packages/ActionBar/README.md
  packages/ActionBar/package.json
  packages/ActionBar/src/components/Filter/DatePicker.js
  packages/ActionBar/src/components/Filter/Filter.js
  packages/ActionBar/src/components/Filter/Filter.styles.js
  packages/ActionBar/src/components/Filter/FilterItem.js
  packages/ActionBar/src/components/Filter/context.js
  packages/ActionBar/src/components/Filter/index.js
  packages/ActionBar/src/components/Filter/rules.js
  packages/ActionBar/src/components/filter.js
  packages/ActionBar/src/hooks/useFilter/index.js
  packages/ActionBar/src/hooks/useFilter/testers.js
  packages/ActionBar/src/hooks/useFilter/useFilter.js
  packages/ActionBar/src/index.d.ts
  packages/ActionBar/src/index.js
  packages/ActionBar/src/types.js
  packages/ActionBar/stories/ShowcaseApp/CustomSingleSelectFilter.js
  packages/ActionBar/stories/ShowcaseApp/ShowcaseApp.js
  packages/ActionBar/stories/examples/CustomButton.js
  packages/ActionBar/tests/cypress/ActionBar.cypress.js
  packages/ActionBar/tests/spec/ActionBar.spec.js
  packages/DatePicker/test/DatePicker.cypress.js
  packages/Filter/README.md
  packages/Filter/src/index.d.ts
  packages/Search/README.md
Labels: Breaking Changes 💥

#885 UXD-745 Standardize Showcase + Variations stories 🐐
  .storybook/assets/styles/common.styles.js
  packages/Button/stories/Button.stories.js
  packages/Button/stories/Button.stories.styles.js
  packages/Button/stories/examples/Showcase.js
  packages/Button/stories/variations/CloseButtonVariations.js
  packages/Button/stories/variations/IconButtonVariations.js
  packages/Button/stories/variations/LinkButtonVariations.js
  packages/Button/stories/variations/Variations.js
  packages/FormElement/stories/FormElement.stories.js
  packages/FormElement/stories/FormElement.stories.styles.js
  packages/FormElement/stories/examples/Showcase.js
  packages/FormElement/stories/examples/Variations.js
  packages/Heading/stories/Heading.stories.js
  packages/Heading/stories/examples/Showcase.js
  packages/Heading/stories/examples/Variations.js
  packages/L10n/stories/L10n.stories.js
  packages/L10n/stories/examples/FakeAppWithContext.js
  packages/L10n/stories/examples/FakeAppWithoutContext.js
  packages/L10n/stories/examples/withLocales/FakeAppWithLocales.js
  packages/Panel/stories/Panel.mdx
  packages/Panel/stories/Panel.stories.js
  packages/Panel/stories/Panel.stories.mdx
  packages/Panel/stories/examples/Showcase.js
  packages/Popover/stories/examples/Showcase.js
  packages/RawButton/stories/RawButton.stories.js
  packages/RawButton/stories/examples/Showcase.js
  packages/RawButton/stories/examples/Variations.js
  packages/ResizeDetector/stories/ResizeDetector.stories.js
  packages/ResizeDetector/stories/examples/Showcase.js
  packages/Toast/stories/Toast.backyard.stories.js
  packages/Toast/stories/Toast.mdx
  packages/Toast/stories/Toast.stories.js
  packages/Toast/stories/Toast.stories.mdx
  packages/Toast/stories/examples/AllKindsExposed.js
  packages/Toast/stories/examples/Screener.js
  packages/Toast/stories/examples/Showcase.js
  packages/Toast/stories/examples/ToastFixedPanel.js
  packages/Toast/stories/examples/Variations.js
Labels: Documentation

#892 UXD-716 Vertical Tabs 🐐
  packages/Tabs/CHANGELOG.md
  packages/Tabs/README.md
  packages/Tabs/package.json
  packages/Tabs/src/Tabs.js
  packages/Tabs/src/components/List/List.js
  packages/Tabs/src/components/Panels/Panels.js
  packages/Tabs/src/components/Tab/Tab.js
  packages/Tabs/src/components/Tab/Tab.styles.js
  packages/Tabs/src/index.d.ts
  packages/Tabs/src/types.js
  packages/Tabs/stories/Tabs.stories.js
  packages/Tabs/stories/examples/Showcase.js
Labels: Breaking Changes 💥
